### ISSUE TITLE
Issue for multiple databases using the `.forRootAsync()`

### ISSUE THREAD

**Issue by OlivierTurci** [mkorobkov/nestjs-slonik#2]
Hi @mkorobkov,

First of all thanks for the repo really nice 👍 

But I unlikely ran into an issue using it related to the use of multiple databases.

I have my first `SlonikModule` that I import in my `app.module.ts` (works fine, it's the default database connection so I don't setup a `name`);
```ts
SlonikModule.forRootAsync({
  imports: [ConfigModule.forFeature(dbConfig)],
  useFactory: async (config: ConfigType<typeof dbConfig>) => ({
    connectionUri: config.uri,
    clientConfigurationInput: {
      interceptors: [createFieldNameTransformationInterceptor(), createResultParserInterceptor()],
    },
  }),
  inject: [dbConfig.KEY],
}),
```
But I do want another database connection so I imported another `SlonikModule` but with a `name` this time
```ts 
// this is the const I use for the name
export const POOL_NAME_GEODATA = 'geodata';
```

```ts
SlonikModule.forRootAsync({
  imports: [ConfigModule.forFeature(dbGeodataConfig)],
  useFactory: async (config: ConfigType<typeof dbGeodataConfig>) => ({
    connectionUri: config.uri,
    name: POOL_NAME_GEODATA,
    clientConfigurationInput: {
      interceptors: [createFieldNameTransformationInterceptor(), createResultParserInterceptor()],
    },
  }),
  inject: [dbGeodataConfig.KEY],
}),
```

But when I try to inject the pool using the `@InjectPool(POOL_NAME_GEODATA)` NestJs cannot resolve the dependencies of the Module (see code below)
```ts
@Injectable()
export class GeodataCountryRepository implements GeodataCountryRepositoryPort {
	protected tableName = 'country';

	protected schema = geodataCountrySchema;

	constructor(
		@InjectPool(POOL_NAME_GEODATA)
		private readonly pool: DatabasePool,
		private readonly mapper: GeodataCountryMapperPort,
	) {}

	async findOneByCode(code: CountryEnum): Promise<GeodataCountry | undefined> {
		const query = sql.type(this.schema)`
			SELECT * 
			FROM ${sql.identifier([this.tableName])} 
			WHERE code = ${code} `;

		const result = await this.pool.query(query);
		if (!result.rows.length) {
			return undefined;
		}

		return this.mapper.toDomain(result.rows[0]);
	}
}
```
NestJs error: `Nest can't resolve dependencies of the GeodataCountryRepository (?, GeodataCountryMapperPort). Please make sure that the argument geodataSlonikPool at index [0] is available in the GeodataModule context.`

I've tried to debug but can't find the reason why it's not working. But while debugging I tried to test using the `.forRoot()` instead of the `.forRootAsync()` and there I saw that it was working and the issue was gone

```ts
SlonikModule.forRoot({
  connectionUri: `postgresql://${process.env.POSTGRES_GEODATA_USER}:${process.env.POSTGRES_GEODATA_PASSWORD}@${
    process.env.POSTGRES_GEODATA_HOST
  }:${parseInt(process.env.POSTGRES_GEODATA_PORT || '', 10) || 5432}/${process.env.POSTGRES_GEODATA_DB}`,
  name: POOL_NAME_GEODATA,
  clientConfigurationInput: {
    interceptors: [createFieldNameTransformationInterceptor(), createResultParserInterceptor()],
  },
})
```

Do you have any idea on why it's not working and what's the issue ? 

PS: if you need any more informations I'll be glad to send those

Thanks,

Olivier

**Comment by mkorobkov** [comment]
Hi Olivier! Thanks for sending an issue. I could reproduce an error. Will check this tomorrow.

**Comment by mkorobkov** [comment]
Hi Olivier, after some research I found the cause of the problem. :)))
There is a small note in the [documentation](https://github.com/mkorobkov/nestjs-slonik/blob/81908d619bda98f718a5d586881e5aca6ff96e23/README.md?plain=1#L289):
> Make sure that the name property is defined at the same level as the useFactory, useClass, or useValue property. This will allow Nest to properly register the pool under the appropriate injection token.

So it should look something like this:
```
SlonikModule.forRootAsync({
  imports: [ConfigModule.forFeature(dbGeodataConfig)],
  name: POOL_NAME_GEODATA,
  useFactory: async (config: ConfigType<typeof dbGeodataConfig>) => ({
    connectionUri: config.uri,
    clientConfigurationInput: {
      interceptors: [createFieldNameTransformationInterceptor(), createResultParserInterceptor()],
    },
  }),
  inject: [dbGeodataConfig.KEY],
}),
```

Please tell me if it works.
